### PR TITLE
 SCT-1682 Queue Status Page

### PR DESCRIPTION
**Pull request by bio-boris**
I used the kbaseCatalogStats.js and catalog_stats.js as a model for these edits.

image

### CODE REVIEW

**Comment by eapearson** [comment]
Nice improvements.

Some general observations:

Should the queue status be available on the main catalog menu or via the jobs plugin (which really just steals parts of the catalog plugin)? As a regular user the "Index" menu option which is used to get to the big honking catalog index is not available. One CAN however get to the queue status by going to the jobs browser and navigating around a bit until the index menu reveals itself (surely a bug).

I think the expanded Catalog menu is triggered by the user being a registered developer. This is probably one reason the jobs browser exists at all -- since it is not easily available through the catalog ui for regular users.

Another issue is that the Jobs Status table is revealed for non-admins. 

Just to check myself -- is it true that the queue status is for all kbase users and the jobs status is just for admins? I make that presumption since the jobs status header reads "(Administrator)"

Finally, at the moment there is an error in the DS call for condor stats (no such item for Cursor instance), but the ui just shows empty tables. Perhaps replace the tables with an error message?

Now a few comments about the specific tables.

generally, any ui issues with the admin tool are less important than the user facing one

Queue Status:

- header could align better with columns

- representation of queue with no available slots might call for something special- presumably it is an outage of some sort. Currently it shows as 100% utilization with a red background.
screen shot 2019-02-08 at 11 32 21 am

- are there plans to define the queues and terms (column headers)? If so there could be tooltips or other help available on this page, and/or links to kbase.us documentation. I didn't find anything in kbase.us when searching for the queue names.

Job Status:

- may not be necessary to show the precise timestamp for submission time. There are ways to represent past timestamps somewhat compactly and helpfully. E.g. "5 minutes ago", "3 days ago", "Feb 3", "Dec 10, 2018". The precise time of day down to the second is perhaps not helpful at a glance, although one could inspect it (mouseover, modal popup) to get more detail.

- table header still breaks apart at about 1400px width; tables are indeed cranky!

**Comment by bio-boris** [comment]
> Should the queue status be available on the main catalog menu or via the jobs plugin (which really just steals parts of the catalog plugin)? As a regular user the "Index" menu option which is used to get to the big honking catalog index is not available. One CAN however get to the queue status by going to the jobs browser and navigating around a bit until the index menu reveals itself (surely a bug). I think the expanded Catalog menu is triggered by the user being a registered developer. This is probably one reason the jobs browser exists at all -- since it is not easily available through the catalog ui for regular users.

I could use your advice on how to proceed with this one.

> Another issue is that the Jobs Status table is revealed for non-admins.
Just to check myself -- is it true that the queue status is for all kbase users and the jobs status is just for admins? I make that presumption since the jobs status header reads "(Administrator)"

This is intentional.   Queue status and Jobs status should be exposed to all users.  Only other people's usernames (and another endpoint for the condor stats service) are exposed for catalog admins. 

> Finally, at the moment there is an error in the DS call for condor stats (no such item for Cursor instance), but the ui just shows empty tables. Perhaps replace the tables with an error message?

Great idea. I didn't think of this possibility until the service actually was busted.

> generally, any ui issues with the admin tool are less important than the user facing one

Very true

>Queue Status:
> header could align better with columns

I'll try to work on this and try to figure out the css issues

> representation of queue with no available slots might call for something special- presumably it is an outage of some sort. Currently it shows as 100% utilization with a red background.

Here's something a bit more special
image


> are there plans to define the queues and terms (column headers)? If so there could be tooltips or other help available on this page, and/or links to kbase.us documentation. I didn't find anything in kbase.us when searching for the queue names.

That's a good idea.  I wonder what we should tell the user's about the queues.  Maybe they should be renamed for the user's consumption, like they are named here: https://kbase.github.io/kb_sdk_docs/references/execution_engine.html 


Job Status:

>  may not be necessary to show the precise timestamp for submission time. There are ways to represent past timestamps somewhat compactly and helpfully. E.g. "5 minutes ago", "3 days ago", "Feb 3", "Dec 10, 2018". The precise time of day down to the second is perhaps not helpful at a glance, although one could inspect it (mouseover, modal popup) to get more detail.

good point, I will remove the seconds.. I  have the service set to update every minute or so, so I could instead change it to static text that says "Updated 1 minute ago"

> table header still breaks apart at about 1400px width; tables are indeed cranky!

Do you have any recommendations on how to fix this? Ideas include having some javascript that runs and tries to set a CSS property for the table headers and makes them a fixed width? Maybe I can try to modify the dynamic table widget ?  Or maybe I try to forgo the dynamic table widget and use datatables on my own so I can configure the CSS my way?

@eapearson Thanks for the great feedback and suggestions

**Comment by eapearson** [comment]
> > Should the queue status be available on the main catalog menu or via the jobs plugin (which really just steals parts of the catalog plugin)? As a regular user the "Index" menu option which is used to get to the big honking catalog index is not available. One CAN however get to the queue status by going to the jobs browser and navigating around a bit until the index menu reveals itself (surely a bug). I think the expanded Catalog menu is triggered by the user being a registered developer. This is probably one reason the jobs browser exists at all -- since it is not easily available through the catalog ui for regular users.
> 
> I could use your advice on how to proceed with this one.

I hate to bounce this back to others, but I think this is an issue for the product owner. There are subjective decisions here. One approach is to support separate sets of tools for different classes of user - e.g. regular user, developer, admin (leaving aside for the moment that each service defines its own class of users, and we have the auth service for roles, ...). Another is to have the tool adjust to the class of the user, disabling or enabling features. In this case we are actually doing both, and that may be unavoidable. I guess I would put more weight on the utility of the end product and the user experience the internal engineering concerns like code duplication, which can be addressed by various means.

> 
> > Another issue is that the Jobs Status table is revealed for non-admins.
> > Just to check myself -- is it true that the queue status is for all kbase users and the jobs status is just for admins? I make that presumption since the jobs status header reads "(Administrator)"
> 
> This is intentional. Queue status and Jobs status should be exposed to all users. Only other people's usernames (and another endpoint for the condor stats service) are exposed for catalog admins.

Okay, cool. So the "(Administrator)" should probably be removed?

> 
> > Finally, at the moment there is an error in the DS call for condor stats (no such item for Cursor instance), but the ui just shows empty tables. Perhaps replace the tables with an error message?
> 
> Great idea. I didn't think of this possibility until the service actually was busted.

I know - busted services are always a great time to work on error handling :)

> 
> > generally, any ui issues with the admin tool are less important than the user facing one
> 
> Very true
> 
> > Queue Status:
> > header could align better with columns
> 
> I'll try to work on this and try to figure out the css issues
> 
> > representation of queue with no available slots might call for something special- presumably it is an outage of some sort. Currently it shows as 100% utilization with a red background.
> 
> Here's something a bit more special
> image

Perfect!
It reminded me of the lyrics "nothing from nothing leaves nothing"...

> 
> > are there plans to define the queues and terms (column headers)? If so there could be tooltips or other help available on this page, and/or links to kbase.us documentation. I didn't find anything in kbase.us when searching for the queue names.
> 
> That's a good idea. I wonder what we should tell the user's about the queues. Maybe they should be renamed for the user's consumption, like they are named here: https://kbase.github.io/kb_sdk_docs/references/execution_engine.html

Yeah, it would be great to tie the queues into defined policies like that. Regular kbase users will probably not have exposure to the sdk docs, and the policies of, resources for, etc. those queues will change over time -- so it would be nice to link to a document like the one you cited above, but oriented to users, and with terms aligned to wherever they may be exposed (narrative, apps, job viewer, queue viewer, etc.)

> 
> Job Status:
> 
> > may not be necessary to show the precise timestamp for submission time. There are ways to represent past timestamps somewhat compactly and helpfully. E.g. "5 minutes ago", "3 days ago", "Feb 3", "Dec 10, 2018". The precise time of day down to the second is perhaps not helpful at a glance, although one could inspect it (mouseover, modal popup) to get more detail.
> 
> good point, I will remove the seconds.. I have the service set to update every minute or so, so I could instead change it to static text that says "Updated 1 minute ago"
> 
> > table header still breaks apart at about 1400px width; tables are indeed cranky!
> 
> Do you have any recommendations on how to fix this? Ideas include having some javascript that runs and tries to set a CSS property for the table headers and makes them a fixed width? Maybe I can try to modify the dynamic table widget ? Or maybe I try to forgo the dynamic table widget and use datatables on my own so I can configure the CSS my way?

Well, at the least the dynamic table widget could use some love, because an issue like keeping column headers together, how to handle overflow within them, how to handle wide tables, etc. are some of the key issues with tabular displays. HTML tables are not especially good at this sort of application, much better for well behaved, static tables.

> 
> @eapearson Thanks for the great feedback and suggestions

**Comment by bio-boris** [comment]
Everything seems to work ok. It's possible to embed this view into the jobs browser by doing
```
             window.KBase.kBaseCatalogQueue(
                {
                    runtime: runtime,
                    usernames: [runtime.service('session').getUsername()],
                    includePublicStats: false,
                    includeUserRunSummary: false,
                    useUserRecentRuns: true,
                    dontShowBackButton: true
                },
                $(container)
            );
```
But the CSS is not quite right. Not sure how to fix that.

I wasn't able to fix the column headers, except by doing a minimum column length of 150. There could be something that can be done with some inline settings on the text and buttons, not I wasn't able to figure out it, even by live editing the css using a jquery selectory.

Otherwise, I believe all other points have been addressed

image
@eapearson

**Comment by eapearson** [comment]
Is there a reason for the large font sizes? We mostly don't use them elsewhere except for headers.
Probably don't need to spell out "Percentage" in the utilization column. Could do "%" or just leave out (since the % is repeated in the cells)
Using H3 for the "You have no queued or running jobs." label is a bit weird - for one it applies the headline font, which is why it looks super bolded -- it is bold applied to an already bold font. 
Also, usage of text shadow is, while not bad in and of itself, not a style we much if at all elsewhere.  Just mentioning.
I'll poke around some more in a bit.

**Comment by bio-boris** [comment]
> Is there a reason for the large font sizes? We mostly don't use them elsewhere except for headers.

I changed it from x-large to large, let me know if I should change something else.

> Probably don't need to spell out "Percentage" in the utilization column. Could do "%" or just leave out (since the % is repeated in the cells)

Fixed

> Using H3 for the danger label is a bit weird - for one it applies the headline font, which is why it looks super bolded -- it is bold applied to an already bold font.

Thanks, I changed it to `<p>`

> Also, usage of text shadow is, while not bad in and of itself, not a style we much if at all elsewhere. Just mentioning.

I did this because otherwise the white text is hard to read when the progress bar is empty

**Comment by eapearson** [comment]
re: the "here" link. Generally one doesn't use "click here" type of link, but make the concept or term itself the link. So, "Learn more about our queues" could just be a link. But this is somewhat subjective.
In either case, the link should open into a new window or tab by setting the attribute target="_blank".

Other than that, I'm good with just merging this in, getting it up on ci, and then letting the actual product owner (Paramvir?) play with it.

If that's what you want, just let me know here or in slack.

**Comment by bio-boris** [comment]
@eapearson I Fixed the link. Sounds good on merging it in.

**Comment by eapearson** [comment]
ok.

**Pull request merged**
